FROM hqsvr:5000/ntrust-worker-lib

RUN apt-get -y install vim-tiny

RUN mkdir /root/.ssh
COPY id_rsa /root/.ssh/
COPY id_rsa.pub /root/.ssh/
COPY known_hosts /root/.ssh/

COPY cmd_start_worker.sh /start_worker.sh
CMD /start_worker.sh
